name: Deploy automático na VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Deploy na VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 147.79.110.139
          username: root
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            git config --global --add safe.directory /root/Odoo-CosturaBrindes
            cd /root/Odoo-CosturaBrindes
            git pull origin main